################################################################################
################################################################################
## FILES AND DIRECTORIES
################################################################################
################################################################################

working_dir: "/home/mstaros1/scr16_rmccoy22/mstarostik/natera_aneuploidy/"  
genotypes_dir: "/data/rmccoy22/natera_spectrum/genotypes/imputed_parents_101224_cpra/"