dbsnp: "/scratch4/rmccoy22/abiddan1/dbsnp/dbSNP151.hg38.vcf.gz"
cpra2rsid_exec: "/scripts/cpra2rsid.py"
ldsc_exec: "/scratch16/rmccoy22/scarios1/sandbox/genetic_correlation/ldsc/ldsc.py"
munge_exec: "/scratch16/rmccoy22/scarios1/sandbox/genetic_correlation/ldsc/munge_sumstats.py"
imputed_parents: "/data/rmccoy22/natera_spectrum/genotypes/imputed_parents_101224_cpra/plink_files/spectrum_imputed_chr22_rehead_filter_plink"
allele_list: "/analysis_files/w_hm3.snplist"
published_ld_scores: "/analysis_files/LDscores_1kgp_EUR/LDscore.@"
calculated_ld_scores: "/results/ld_scores/LDscore.@"
published_summary_stats: "/scratch16/rmccoy22/abiddan1/prs_aneuploidy/analysis/pgs_calc/results"
aneuploidy_summary_stats: "/scratch16/rmccoy22/scarios1/natera_aneuploidy/analysis/gwas/results/gwas/summary_stats"
recombination_summary_stats: "/scratch16/rmccoy22/abiddan1/natera_recomb/analysis/gwas/results/gwas_output/regenie"

summary_stats:
  maternal_meiotic_aneuploidy_by_mother:
    file: "{aneuploidy_summary_stats}/lmm_gwas_maternal_meiotic_aneuploidy_by_mother_discovery_total.tsv.gz"
    type: "aneuploidy"
    N: 12000
    ld_scores: "/results/intermediate_files/ldscore@"
  mean_crossovers_by_mother:
    file: "{recombination_summary_stats}/natera_recombination_gwas_Female_regenie.MeanCO.glm.linear"
    type: "recombination"
    N: 14788
    ld_scores: "/results/intermediate_files/ldscore@"
  telomere_distance_by_mother:
    file: "{recombination_summary_stats}/natera_recombination_gwas_Female_regenie.TelomereDist.glm.linear"
    type: "recombination"
    N: 14776
    ld_scores: "/results/intermediate_files/ldscore@"
  centromere_distance_by_mother:
    file: "{recombination_summary_stats}/natera_recombination_gwas_Female_regenie.CentromereDist.glm.linear"
    type: "recombination"
    N: 14875
    ld_scores: "/results/intermediate_files/ldscore@"
  ovarian_aging_ANM_reproGen:
    file: "{published_summary_stats}/ovarian_aging_pgs.reprogen.ANM.rsids.true.tsv"
    type: "reprogen2021" 
    N: 200000
    ld_scores: "{published_ld_scores}"
  age_at_menarche_reproGen:
    file: "{published_summary_stats}/age_at_menarche_reproGen.rsids.true.tsv"
    type: "reprogen2024"
    N: 503943
    ld_scores: "{published_ld_scores}"
  all_cause_female:
    file: "{published_summary_stats}/all_cause_female.rsids.true.tsv"
    type: "venkatesh2024"
    N: 366090
    ld_scores: "{published_ld_scores}"
  anatomical_female:
    file: "{published_summary_stats}/anatomical_female.rsids.true.tsv"
    type: "venkatesh2024"
    N: 319411
    ld_scores: "{published_ld_scores}"
  anovulatory_female:
    file: "{published_summary_stats}/anovulatory_female.rsids.true.tsv"
    type: "venkatesh2024"
    N: 195950
    ld_scores: "{published_ld_scores}"
  idiopathic_exclusion_female:
    file: "{published_summary_stats}/idiopathic_exclusion_female.rsids.true.tsv"
    type: "venkatesh2024"
    N: 430388
    ld_scores: "{published_ld_scores}"
  idiopathic_inclusion_female:
    file: "{published_summary_stats}/idiopathic_inclusion_female.rsids.true.tsv"
    type: "venkatesh2024"
    N: 292276 
    ld_scores: "{published_ld_scores}"
  male_infertility:
    file: "{published_summary_stats}/male_infertility.rsids.true.tsv"
    type: "venkatesh2024"
    N: 244567
    ld_scores: "{published_ld_scores}"