afs: "utils/HumanCytoSNP-12v2-1_NS550_A1.hg38.annotated.autosomes.total.1kg_af.txt.gz"
hmm_sims:
  model_comp: true
  mixed_ploidy: true
  simple_sims:
    reps: 40
    ploidy:
      - 0
      - 1
      - 2
      - 3
    m:
      - 4000
    std_dev:
      - 15
      - 20
      - 25
      - 30
      - 35
    pi0:
      - 40
    skew:
      - 100
  mixed_sims:
    reps: 20
    p_mono:
      - 0
      - 10
      - 30
      - 50
      - 70
    p_tri:
      - 0
      - 10
      - 30
      - 50
      - 70
    m:
      - 4000
    std_dev:
      - 15
      - 20
      - 30
    pi0:
      - 40
    skew:
      - 100
    ncells:
      - 5
      - 10
