afs: "utils/HumanCytoSNP-12v2-1_NS550_A1.hg38.annotated.autosomes.total.1kg_af.txt.gz"
hmm_sims:
  model_comp: True
  mixed_ploidy: True
  fpr: True
  eps: -6
  simple_sims:
    reps: 5
    ploidy:
      - 1
      - 2
      - 3
    m:
      - 4000
    std_dev:
      - 20
      - 30
      - 40
    pi0:
      - 30
      - 40
    skew:
      - 50
  mixed_sims:
    reps: 20
    p_aneuploid:
      #- 5
      #- 10
      - 20
      - 30
      - 40
      - 50
    m:
      - 1000
    std_dev:
      #- 10
      - 20
      #- 30
      #- 40
    pi0:
      #- 20
      - 40
      #- 60
    skew:
      #- 10
      - 50
      #- 90
    ncells:
      - 5
      - 10
  fpr_sims:
    reps: 5
    ploidy:
      - 0
      - 1
      - 2
      - 3
    m:
      - 5000
    pi0:
      - 30
    std_dev:
      - 30
    skew:
      - 0
