afs: "utils/HumanCytoSNP-12v2-1_NS550_A1.hg38.annotated.autosomes.total.1kg_af.txt.gz"
hmm_sims:
  model_comp: True
  mixed_ploidy: True
  fpr: False 
  simple_sims:
    reps: 20
    ploidy:
      - 0
      - 1
      - 2
      - 3
    m:
      - 5000
    std_dev:
      - 15
      - 20
      - 25
      - 30
      - 35
      - 40
      - 45
      - 50
    pi0:
      - 20
      - 40
    skew:
      - 100
  mixed_sims:
    reps: 20
    p_mono:
      - 0
      - 10
      - 30
      - 50
      - 70
    p_tri:
      - 0
      - 10
      - 30
      - 50
      - 70
    m:
      - 5000
    std_dev:
      - 20
      - 30
      - 40
    pi0:
      - 20
      - 40
    skew:
      - 0
    ncells:
      - 5
      - 10
  fpr_sims:
    reps: 500
    ploidy:
      - 0
      - 1
      - 2
      - 3
    m:
      - 5000
    pi0:
      - 60
    std_dev:
      - 20
    skew:
      - 0
