#!/usr/bin/env python3

shell.prefix("""
set -o pipefail
set -e
""")

"""
author: Margaret R. Starostik, Biology Dept., Johns Hopkins University
email: mstaros1@jhu.edu
last update: August 7, 2024
aim: 

Listed below are some useful commands.

I use the following custom Python environment:
ml anaconda
conda activate snakemake-env

(1) Perform dry run.
snakemake --snakefile twas_snakefile --dryrun --printshellcmds --rerun-incomplete

(2) Visualize workflow.
snakemake --snakefile twas_snakefile --dag 2> /dev/null |dot -T pdf > twas_workflow.pdf

(3) Track changes to code.
snakemake --snakefile twas_snakefile --list-code-changes

(4) Unlock.
snakemake --snakefile twas_snakefile --unlock --rerun-incomplete

(5) Use snakemake to submit each job to slurm scheduler:
ssh devrmccoy1

ml anaconda
conda activate snakemake-env

cd /home/mstaros1/scr16_rmccoy22/mstarostik/natera_aneuploidy/code

snakemake \
--snakefile twas_snakefile \
--profile /home/mstaros1/.config/snakemake/ >& twas_snakefile.log
"""

################################################################################
################################################################################
## TOOLS
################################################################################
################################################################################

import glob
import re
from os.path import join, basename
from snakemake.utils import R

################################################################################
################################################################################
## PIPELINE CONFIGURATION
################################################################################
################################################################################

configfile: "/home/mstaros1/scr16_rmccoy22/mstarostik/natera_aneuploidy/code/config_twas.yaml"

WORKING_DIR = config["working_dir"]
GENOTYPES_DIR = config["genotypes_dir"]

################################################################################
################################################################################
## VARIABLES
################################################################################
################################################################################

# GTEx v8 tissues
#TISSUES = ["Adipose_Subcutaneous"]
TISSUES = [re.sub("mashr_", "", os.path.basename(fname).split('.')[0]) for fname in glob.glob(os.path.join(WORKING_DIR + "data/GTEx_v8/eqtl/mashr", "*.db"))]

# chromosomes
CHROMOSOMES = range(1,24)

################################################################################
################################################################################
## DESIRED OUTPUT (BE CAREFUL OF TEMPORARY FILES THAT ARE DELETED!)
################################################################################
################################################################################

# predicted expression
PRED = expand(WORKING_DIR + "analysis/twas/predict_expression/{tissue}_chr{chromosome}_predict.txt", tissue = TISSUES, chromosome = CHROMOSOMES),

# test associations
ASSOC = expand(WORKING_DIR + "analysis/twas/association/{tissue}_chr{chromosome}_association.txt", tissue = TISSUES, chromosome = CHROMOSOMES)

################################################################################
################################################################################
## LOCAL RULES: RULES THAT CAN BE RUN LOCALLY
################################################################################
################################################################################

localrules: all

"""
RULE ALL: snakemake accepts rule names as targets if the referred rule does not
have wildcards. If no target is given at command line at the top of the
workflow, snakemake will define the first file of the snakefile as the target.
Therefore, it is best practice to have a "RULE ALL" at the top of the WORKFLOW
which has all the desired target files of the pipeline as input files.
"""

rule all:
    input:
        PRED,
        ASSOC
        
               
################################################################################
################################################################################
## RULES
################################################################################
################################################################################

include: "/home/mstaros1/scr16_rmccoy22/mstarostik/SNAKEMAKE/TWAS/predict_expression_from_GTEXv8_mashr.smk"
